esp32:
  board: esp32dev # dfrobot_firebeetle2_esp32ue
  framework:
    type: arduino
    version: recommended

esphome:
  name: eink-frame-${device_id}
  friendly_name: "eink frame ${device_id}"
  platformio_options:
    build_flags: "-DBOARD_HAS_PSRAM"

substitutions:
  device_id: "DEVICE_ID"

  clk_pin: "GPIO18"
  mosi_pin: "GPIO23"
  cs_pin: "GPIO15"
  dc_pin: "GPIO13"
  busy_pin: "GPIO04"
  reset_pin: "GPIO14"
  # power_pin: "3v3"
