substitutions:
  device_id: "example_waveshare"
  wifi_ssid: !secret wifi_ssid
  wifi_password: !secret wifi_password
  wake_up_time: "04:00:00"
  image_url: "http://homeassistant.local:8090/displays/queue.png"

  clk_pin: "GPIO13"
  mosi_pin: "GPIO14"
  cs_pin: "GPIO15"
  dc_pin: "GPIO27"
  busy_pin: "GPIO25"
  reset_pin: "GPIO26"

  waveshare_model: "13.3in-k" # or another waveshare model

esp32:
  board: esp-wrover-kit
  framework:
    type: arduino
    version: recommended
