name: dev-env
channels:
- defaults
- conda-forge
dependencies:
- python=3.11

- ipywidgets
- jinja2
- jupyterlab
- jupytext
- matplotlib
- mypy
- numpy
- pandas
- pre-commit
- pytest
- pytorch
- scipy

- pip
- pip:
  - accelerate
  - diffusers
  - huggingface_hub
  - invisible-watermark
  - sentencepiece
  - tdqm
  - torch
  - torchaudio
  - torchvision
  - transformers
