name: dev-env
channels:
- defaults
- conda-forge
dependencies:
- python=3.11

- ipywidgets
- jinja2
- jupyterlab
- jupytext
- pytorch
- matplotlib
- mypy
- numpy
- pandas
- pip
- pre-commit
- pytest
- scipy
- diffusers
- transformers
- invisible-watermark
- huggingface_hub=0.20
- pip:
  - tdqm
  - invisible-watermark
