name: "Canvas Coordinator"
description: "Server for generating and selecting images for e-ink displays"
version: "1.0.0"
slug: "canvas_coordinator"
init: false
arch:
  - aarch64
  - amd64
  - armhf
  - armv7
  - i386
options:
  username: "email"
  password: "password"
  wait_time: 60
  log_level: INFO
schema:
  username: str
  password: password
  wait_time: int
  log_level: list(TRACE|DEBUG|INFO|WARN|ERROR)
