name: "Canvas Coordinator"
description: "Server for generating and selecting images for e-ink displays"
version: "1.2.10"
slug: "canvas_coordinator_prime"
init: false
arch:
  - aarch64
  - amd64
  - armhf
  - armv7
  - i386
options:
  log_level: INFO
schema:
  log_level: list(TRACE|DEBUG|INFO|WARN|ERROR)
ports:
  8080/tcp: null
webui: "http://[HOST]:[PORT:8080]"
