
esphome:
  name: epaperdisplay
  on_boot:
    priority: -10
    then:
      - logger.log: "not displayed image"
      - delay: 1s
      - logger.log: "not not displayed image"
      - component.update: my_display
      - logger.log: "changed"
esp32:
  board: esp32dev
  framework:
    type: arduino
    version: recommended

logger:
  baud_rate: 115200
  level: DEBUG

debug:
  update_interval: 2s

sensor:
  - platform: debug
    free:
      name: "Heap Free"
    block:
      name: "Heap Max Block"
    # psram:
    #   name: "PSRAM"
# psram:
#   id: my_psram
#   speed: 80MHz
image:
  - file: images/test.png
    id: my_image
    resize: 960x680
    type: BINARY
    dither: FLOYDSTEINBERG

spi:
  # esp32-epaper driver
  clk_pin: 13
  mosi_pin: 14 # this might also refer to SPI DIN
display:
  - platform: waveshare_epaper
    id: my_display

    # esp32-epaper-driver no HAT
    cs_pin: 15
    dc_pin: 27
    busy_pin:  25
    reset_pin: 26

    model: 13.3in-k
    update_interval: never
    lambda: |-
      it.image(0, 0, id(my_image));
      ESP_LOGD("display", "Image displayed successfull");

deep_sleep:
  run_duration: 9s
  sleep_duration: 1s

