http_request:
  id: fetch_image_request
  timeout: 5s
  useragent: esphome/example_device
  verify_ssl: false

esphome:
  name: epaperdisplay
  on_boot:
    priority: -10
    then:
      - logger.log: "not displayed image"
      - delay: 1s
      - logger.log: "not not displayed image"
      - component.update: my_display
      - logger.log: "changed"
esp32:
  board: dfrobot_firebeetle2_esp32s3
  framework:
    type: arduino
    version: recommended

logger:
  baud_rate: 115200
  level: VERY_VERBOSE

debug:
  update_interval: 2s

sensor:
  - platform: debug
    free:
      name: "Heap Free"
    block:
      name: "Heap Max Block"

deep_sleep:
  run_duration: 15s
  sleep_duration: 1s

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  on_connect:
    - component.update: my_image

online_image:
  - url: http://192.168.1.249:8000/images/800x480/image.png
    id: my_image
    format: png
    resize: 800x480
    type: BINARY
    on_download_finished:
      then:
        - component.update: my_display
        - logger.log: "Downloaded image"
    on_error:
      then:
        - logger.log: "Error downloading image"

spi:
  clk_pin: 12
  mosi_pin: 11

display:
  - platform: waveshare_epaper
    id: my_display

    cs_pin: 10
    dc_pin: 9
    busy_pin:
      number: 7
      inverted: true
    reset_pin: 4

    model: 7.50inV2alt
    reset_duration: 200ms
    update_interval: never
    # the colors are inverted, i have no idea why
    lambda: |-
      it.image(0, 0, id(my_image));
      ESP_LOGD("display", "Image displayed successfull");
