
# Problem, the esp32 wakes up at 0350, when it should be waking up at 0400,
# the sleeps for 10 mins and wakes up again.
# We can calculate the number of hours to sleep ourselves, checking if it wokeup too early.

http_request:
  id: fetch_image_request
  timeout: 5s
  useragent: esphome/eink_display
  verify_ssl: false

deep_sleep:
  id: deep_sleep_control
  run_duration: 1min
  sleep_duration: "86400sec"

time:
  - platform: sntp
    id: time_sntp
    on_time_sync:
      then:
        lambda: |-
            uint32_t target_hour = 4;  // 4 AM

            uint32_t current_hour = id(time_sntp).now().hour;
            uint32_t current_minute = id(time_sntp).now().minute;
            ESP_LOGD("deep_sleep_calculation", "target hour %d", target_hour);
            ESP_LOGD("deep_sleep_calculation", "Current hour %d", current_hour);
            ESP_LOGD("deep_sleep_calculation", "Current min %d", current_minute);

            time_t currTime = id(time_sntp).now().timestamp;
            time_t next_wake_up_timestamp;

            // Ensure next wake-up is about 24h in the future
            uint32_t sleep_duration = (24)*3600;

            if (current_hour < target_hour) {
              ESP_LOGD("deep_sleep_calculation", "It is still today");
              sleep_duration += (target_hour - current_hour)*3600;
              sleep_duration += (current_minute * 60);
            }
            else {
              ESP_LOGD("deep_sleep_calculation", "It is tomorrow");
              sleep_duration -= (target_hour - current_hour)*3600;
              sleep_duration -= (current_minute * 60);
            }

            // Log the sleep duration (for debugging purposes)
            ESP_LOGD("deep_sleep_calculation", "Calculated sleep duration: %d seconds", sleep_duration);

            // Update sleep duration, function takes mili sec
            sleep_duration = sleep_duration * 1000;
            id(deep_sleep_control).set_sleep_duration(sleep_duration);

logger:
  baud_rate: 115200
  level: DEBUG

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  power_save_mode: light
  on_connect:
    - logger.log: WiFi is connected!
    - logger.log: "Trying to download image"
    - component.update: my_image

captive_portal:

online_image:
  - url: "http://homeassistant.local:8090/displays/queue.png"
    id: my_image
    format: png
    type: BINARY
    on_download_finished:
      then:
        - logger.log: "Downloaded image, updating display"
        - display.page.show: page1
        - component.update: my_display
        - delay: 7s
        - deep_sleep.enter:
            id: deep_sleep_control
    on_error:
      then:
        - logger.log: "Error downloading image"
        - display.page.show: page2
        - component.update: my_display
        - delay: 7s
        - deep_sleep.enter:
            id: deep_sleep_control

spi:
  clk_pin: $clk_pin
  mosi_pin: $mosi_pin

display:
  - platform: waveshare_epaper
    id: my_display
    cs_pin: $cs_pin
    dc_pin: $dc_pin
    busy_pin:
      number: $busy_pin
      inverted: $busy_pin_inverted
    reset_pin: $reset_pin
    reset_duration: 200ms
    model: $waveshare_model
    update_interval: never
    pages:
      - id: page1
        lambda: |-
          it.image(0, 0, id(my_image), Color::BLACK, Color::WHITE);
          ESP_LOGD("display", "Image displayed successfully");
      - id: page2
        lambda: |-
          it.line(0, 0, 50, 50);
          it.line(0, 50, 50, 0);
          ESP_LOGD("display", "Error Image displayed successfully");

api:
  on_client_connected:
    then:
      - sensor.template.publish:
          id: battery_level
          state: !lambda "return id(battery_level).state;"
      - sensor.template.publish:
          id: battery_voltage
          state: !lambda "return id(battery_voltage).state;"

ota:
  - platform: esphome

sensor:
  # https://esphome.io/components/sensor/adc.html#measuring-battery-voltage-on-the-firebeetle-esp32-e
  - platform: adc
    id: battery_voltage
    name: "Battery voltage"
    pin: ${vdd_pin}
    accuracy_decimals: 2
    update_interval: 60s
    attenuation: 12dB
    samples: 3
    filters:
      - multiply: 2.0  # The voltage divider requires us to multiply by 2
    on_value:
      then:
        - logger.log: "Battery Voltage: ${sensor.battery_voltage} V"

  - platform: template
    name: "Battery Level"
    id: battery_level
    unit_of_measurement: "%"
    accuracy_decimals: 0
    lambda: |-
      float voltage = id(battery_voltage).state;
      if (voltage < 3.0) return 0;
      if (voltage > 4.2) return 100;
      return (voltage - 3.0) / (4.2 - 3.0) * 100.0;

binary_sensor:
  - platform: status
    name: "${device_id} Status"
    id: device_status
