version: 1
disable_existing_loggers: False
formatters:
  default:
    datefmt: '%Y-%m-%d %H:%M:%S'
    # "()": uvicorn.logging.DefaultFormatter
    format: '%(asctime)s - %(levelname)s - %(message)s (%(name)s)'
  access:
    # "()": uvicorn.logging.AccessFormatter
    datefmt: '%Y-%m-%d %H:%M:%S'
    format: '%(asctime)s - %(levelname)s - %(message)s (%(name)s)'
handlers:
  default:
    formatter: default
    class: logging.StreamHandler
    stream: ext://sys.stderr
  access:
    formatter: access
    class: logging.StreamHandler
    stream: ext://sys.stdout
loggers:
  uvicorn.error:
    level: INFO
    handlers:
      - default
    propagate: no
  uvicorn.access:
    level: INFO
    handlers:
      - access
    propagate: no
root:
  level: INFO
  handlers:
    - default
  propagate: no
