esphome:
  name: epaperdisplay
  board: esp32dev
  platform: ESP32
  on_boot:
    - priority: -10
      then:
        - wait_until: 
            condition:
              wifi.connected:
            timeout: 20s
        - delay: 1s
        - logger.log: "Connected to WiFi"
        - component.update: my_image
        - logger.log: "downloaded image"
        - delay: 15s
        - component.update: my_display
        - logger.log: "displayed image"

logger:
  baud_rate: 115200
  level: DEBUG
# esp32:
#   board: esp32s3box
#   variant: esp32s3
#   framework:
#     type: arduino
#     version: recommended
spi:
  # esp32-epaper driver
  clk_pin: 13
  mosi_pin: 14 # this might also refer to SPI DIN
  # other
  # clk_pin: 13
  # mosi_pin: 12 # this might also refer to SPI DIN
debug:
  update_interval: 5s
sensor:
  - platform: debug
    free:
      name: "Heap Free"
    block:
      name: "Heap Max Block"
    # psram:
    #   name: "PSRAM"
#define PIN_SPI_SCK  12
#define PIN_SPI_DIN  13
#define PIN_SPI_CS   10
#define PIN_SPI_BUSY 7 //19
#define PIN_SPI_RST  8 //21
#define PIN_SPI_DC   9 //22
#define PIN_SPI_PWR  6 //22
# image:
#   - file: http://192.168.1.138:8000/test.png
#     id: my_image
#     resize: 960x680
#     type: BINARY
#     dither: FLOYDSTEINBERG

display:
  - platform: waveshare_epaper
    id: my_display

    # esp32-wrover-dev
    # esp32-epaper-driver
    cs_pin: 15
    dc_pin: 27
    busy_pin:  25
    reset_pin: 26

    # wroom
    # cs_pin: 27
    # dc_pin: 25
    # busy_pin:  32
    # reset_pin: 33

    # esp32-s3
    # cs_pin: 10
    # dc_pin: 9
    # busy_pin: 7
    # reset_pin: 8

    model: 13.3in-k
    update_interval: never
    lambda: |-
      it.image(0, 0, id(my_image), COLOR_OFF, COLOR_ON);


wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  manual_ip:
      # Set this to the IP of the ESP
      static_ip: 192.168.1.86
      # Set this to the IP address of the router. Often ends with .1
      gateway: 192.168.1.1
      # The subnet of the network. 255.255.255.0 works for most home networks.
      subnet: 255.255.255.0

deep_sleep:
  run_duration: 300s
  sleep_duration: 5s

external_components:
  - source: github://pr#6443
    components: [waveshare_epaper]
  # - source: ../../../esphome/esphome/components 
  #   components: [ online_image, display ]
  - source: github://pr#4710
    components: [online_image, display]
online_image:
  - url: http://192.168.1.138:8000/current.png
  # - url: http://www.libpng.org/pub/png/img_png/pnglogo-blk-tiny.png
  #- url: http://192.168.1.138:8000/black.png
    id: my_image
    format: PNG
    resize: 574x408 #720x510 #960x680 
    type: BINARY
    # buffer_size: 81600
    on_download_finished:
      then:
        - logger.log: "Downloaded image"
    on_error:
      then:
        - logger.log: "Error downloading image"

