substitutions:
  spi_clk_pin: "12"
  spi_mosi_pin: "11"
  display_cs_pin: "10"
  display_dc_pin: "9"
  display_busy_pin: "7"
  display_reset_pin: "4"

esphome:
  name: epaperdisplay
  on_boot:
    priority: -10
    then:
      - logger.log: "before my_display"
      - component.update: my_display
      - logger.log: "changed, hopefully"

esp32:
  board: dfrobot_firebeetle2_esp32s3
  framework:
    type: arduino
    version: recommended

logger:
  baud_rate: 115200
  level: INFO

debug:
  update_interval: 2s

sensor:
  - platform: debug
    free:
      name: "Heap Free"
    block:
      name: "Heap Max Block"

image:
  - file: ../../images/960x680/test.png
    id: my_image
    resize: 960x680
    type: BINARY
    dither: FLOYDSTEINBERG

spi:
  clk_pin: ${spi_clk_pin}
  mosi_pin: ${spi_mosi_pin}

display:
  - platform: waveshare_epaper
    id: my_display
    cs_pin: ${display_cs_pin}
    dc_pin: ${display_dc_pin}
    busy_pin: ${display_busy_pin}
    reset_pin: ${display_reset_pin}
    reset_duration: 300ms
    model: 13.3in-k
    update_interval: never
    lambda: |-
      it.image(0, 0, id(my_image));
      ESP_LOGD("display", "Image displayed successfully");

deep_sleep:
  run_duration: 20s
  sleep_duration: 1s
