http_request:
  id: fetch_image_request
  timeout: 5s
  useragent: esphome/eink_display
  verify_ssl: false

substitutions:
  device_id: "default_id"  # This will be overridden when flashing

esphome:
  name: eink_frame_${device_id}
  friendly_name: "${device_id}"
  device_id: eink_frame_${device_id}  # Replace with a unique identifier for each device

esp32:
  board: dfrobot_firebeetle2_esp32s3
  framework:
    type: arduino
    version: recommended

time:
  - platform: sntp
    id: sntp_time

deep_sleep:
  id: deep_sleep_control
  run_duration: 2min  # Fallback duration if something goes wrong
  sleep_duration:
    lambda: |-
      if (id(sntp_time).is_synced()) {
        auto now = id(sntp_time).now();
        auto wake_time = id(sntp_time).make_time(now.year, now.month, now.day_of_month, 4, 0, 0);
        if (now.hour >= 4) {
          wake_time = wake_time.timestamp + 24 * 60 * 60;  // Add 24 hours if it's past 4 AM
        }
        return (wake_time.timestamp - now.timestamp) * 1000;  // Convert to milliseconds
      } else {
        ESP_LOGW("deep_sleep", "SNTP not synced, falling back to 24-hour sleep");
        return 24 * 60 * 60 * 1000;  // 24 hours in milliseconds
      }

logger:
  baud_rate: 115200
  level: DEBUG

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  on_connect:
    - component.update: my_image

online_image:
  - url: http://homeassistant.local:8099/api/image.png
    id: my_image
    format: png
    type: BINARY
    on_download_finished:
      then:
        - component.update: my_display
        - logger.log: "Downloaded image"
    on_error:
      then:
        - logger.log: "Error downloading image"
        - delay: 5s
        - deep_sleep.enter: deep_sleep_control

spi:
  clk_pin: 12
  mosi_pin: 11

display:
  - platform: waveshare_epaper
    id: my_display

    cs_pin: 10
    dc_pin: 9
    busy_pin: 7
    reset_pin: 4
    reset_duration: 200ms

    model: 13.3in-k
    update_interval: never
    # the colors are inverted, i have no idea why
    lambda: |-
      it.image(0, 0, id(my_image), Color::BLACK, Color::WHITE);
      ESP_LOGD("display", "Image displayed successfully");
      id(deep_sleep_control).begin_sleep();  # Enter deep sleep after display update

api:
  # Remove the encryption key
ota:
